# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

In [1]:
import numpy as np


1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [3]:
arr = np.random.uniform(low = 0, high = 20, size = (4,7))
arr 

array([[10.47908987, 15.54320463, 14.22506038, 12.61973574, 15.09258679,
        17.87310883,  0.16143984],
       [ 8.37692463,  9.89028998, 14.83882158,  2.99651752,  6.28176369,
        13.17335254,  8.84777546],
       [14.37650302,  7.17838231, 18.32287492, 15.604688  , 12.11790535,
        10.73032276,  7.92593925],
       [ 6.03200447,  5.22310495, 19.13030719,  1.07804795,  6.96494555,
         2.15099818,  2.61460154]])

In [7]:
(arr - arr.min()) / (arr.max() - arr.min())

array([[1.        , 0.71491457, 0.70977459, 0.65598887, 0.01962121,
        0.36806473, 0.05490899],
       [0.0580746 , 0.02629867, 0.96094436, 0.51848614, 0.66660122,
        0.91130738, 0.5592069 ],
       [0.98292174, 0.27210626, 0.63454427, 0.91839229, 0.2911465 ,
        0.16409995, 0.05574912],
       [0.69051907, 0.09236212, 0.56610923, 0.        , 0.46088343,
        0.70729263, 0.26309883]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [6]:
arr = np.random.randint(low = 0, high = 10, size = (8,10))
arr

array([[6, 9, 1, 2, 8, 8, 4, 9, 8, 9],
       [7, 9, 6, 0, 7, 4, 2, 4, 9, 6],
       [5, 8, 3, 5, 2, 5, 5, 0, 8, 9],
       [6, 0, 1, 7, 8, 8, 5, 2, 6, 2],
       [3, 2, 2, 8, 7, 8, 1, 3, 2, 6],
       [1, 9, 4, 7, 9, 3, 9, 9, 4, 0],
       [5, 7, 4, 4, 8, 7, 6, 6, 4, 8],
       [3, 8, 0, 3, 7, 0, 1, 1, 1, 1]])

In [7]:
arr[:, 3]

array([2, 0, 5, 7, 8, 7, 4, 3])

In [19]:
arr.sum(axis = 1)

array([64, 54, 50, 45, 42, 55, 59, 25])

In [20]:
sum_by_row = arr.sum(axis = 1)
min_idx = sum_by_row.argmin()
min_idx, arr[min_idx], arr[min_idx].sum()

(7, array([3, 8, 0, 3, 7, 0, 1, 1, 1, 1]), 25)

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [21]:
x = np.array([1,2,3])
y = np.array([1,4,3])
np.sqrt(np.power(x-y,2).sum())

2.0

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [31]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

In [32]:
X = np.linalg.inv(A) @ (-C) @ np.linalg.inv(B)
X

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

In [39]:
A @ X @ B 

array([[ -7., -21.],
       [-11.,  -8.],
       [ -8.,  -4.]])

In [41]:
-C

array([[ -7, -21],
       [-11,  -8],
       [ -8,  -4]])

## Лабораторная работа №1

__При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.__

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [37]:
data = np.loadtxt(fname = 'minutes_n_ingredients.csv', dtype = str, delimiter = ',')

In [38]:
data[:6,:]

array([['id', 'minutes', 'n_ingredients'],
       ['127244', '60', '16'],
       ['23891', '25', '7'],
       ['94746', '10', '6'],
       ['67660', '5', '6'],
       ['157911', '60', '14']], dtype='<U13')

In [90]:
data[1:,1:]

array([['60', '16'],
       ['25', '7'],
       ['10', '6'],
       ...,
       ['65', '15'],
       ['5', '4'],
       ['140', '14']], dtype='<U13')

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [655]:
data_new = data[1:,:].astype(np.int)

inf = ['Среднее','Минимум','Максимум']
minutes_mean = [data_new[:,1].mean(), data_new[:,1].min(), data_new[:,1].max()] # Среднее, мин и макс по минутам
ingr_mean = [data_new[:,2].mean(), data_new[:,2].min(), data_new[:,2].max()]    # Среднее, мин и макс по ингридиентам

np.matrix([inf,minutes_mean,ingr_mean])

matrix([['Среднее', 'Минимум', 'Максимум'],
        ['21601.00169', '0', '2147483647'],
        ['9.05528', '1', '39']], dtype='<U11')

3. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [654]:
ten_rand_inf = data_new[np.random.randint(low = 0, high = len(data_new[:,0]), size = 10)]
ten_rand_inf

array([[347632,     20,     10],
       [272438,     22,      5],
       [270397,     30,      8],
       [ 66848,     45,     10],
       [292914,     25,      3],
       [308656,     20,      8],
       [309788,     30,      6],
       [185203,     25,      9],
       [ 86315,     90,     14],
       [ 30583,     20,      7]])

4. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [152]:
data_new.shape

(100000, 3)

In [154]:
five_ing = data_new[data_new[:,2] <= 5]
five_ing

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

5. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [182]:
print((data_new[data_new[:,2] < ingr_mean[0]].shape[0] / data_new.shape[0]) * 100,'%')

58.802 %


In [649]:
ingr_mean[0]

9.05528

6. Вычислите значение $q_{0.75}$ третьего квартиля продолжительности выполнения рецепта. Замените в этом столбце значения, большие чем $q_{0.75}$ на величину $q_{0.75}$.

In [190]:
q_075 = data_new[int(data_new.shape[0]*0.75)][1]
q_075

65

In [646]:
q_075_col = np.where(data_new[:,1] > q_075,data_new[:,1],q_075)

# data_new[:,1] > q_075
# a = np.arange(10)
# a
# np.where(a != 3, a, 65)

In [229]:
q_075_data = np.matrix([data_new[:,0],q_075_col,data_new[:,2]])
q_075_data.reshape((100000,3))

matrix([[127244,  23891,  94746],
        [ 67660, 157911, 152828],
        [ 33941, 446597, 366174],
        ...,
        [     5,      4,     10],
        [     8,      7,     15],
        [    15,      4,     14]])

In [648]:
q_075_data

matrix([[127244,  23891,  94746, ..., 498432, 370915,  81993],
        [    65,     65,     65, ...,     65,     65,    140],
        [    16,      7,      6, ...,     15,      4,     14]])

In [647]:
np.where(data_new[:,1] > q_075, q_075,data_new[:,1])

array([60, 25, 10, ..., 65,  5, 65])

7. Посчитайте, для скольких рецептов исходного массива указана продолжительность, равная нулю. Модифицируйте исходный массив, заменив для таких строк значение в данном столбце на 1.

In [248]:
data_new[:,1].min()

0

In [645]:
# кол-во 0 в столбце minutes
np.unique(data_new[:,1], return_index = True)[1][0]


411

In [265]:
np.where(data_new == 0, 1,data_new)

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])

8. Найдите множество возможных значений величины количества ингредиентов и количество вхождений каждого из уникальных значений в набор данных. Используя `numpy.isin`, выясните, какие числа из отрезка [1, 41] отсуствуют в данном множестве и выведите их на экран. 

In [290]:
#set(np.arange(1,42)),(set(data_new[:,2]))

In [396]:
values, counts = (np.unique(data_new[:,2], return_counts = True))
values, counts

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39]),
 array([   13,   926,  2895,  5515,  7913,  9376, 10628, 10951, 10585,
         9591,  8297,  6605,  4997,  3663,  2595,  1767,  1246,   790,
          573,   376,   217,   161,   105,    69,    50,    28,    16,
           16,    12,    12,     3,     1,     2,     1,     3,     1,
            1], dtype=int64))

In [291]:
set(np.arange(1,42)) - (set(data_new[:,2]))


{36, 38, 40, 41}

In [391]:
np.isin(set(np.arange(1,42)),set(data_new[:,2]))

array(False)

9. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета.

In [311]:
data_new[:,2] 

array([16,  7,  6, ..., 15,  4, 14])

In [339]:
print((data_new[:,2] / np.where(data_new[:,1] == 0, 1, data_new[:,1])).max(),'- максимальное значение')

24.0 - максимальное значение


10. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [370]:
#1
min_without_0 = np.where(data_new[:,1] == 0, 1, data_new[:,1])
top_100 = np.sort(min_without_0)[::-1][:100]

In [418]:
indexes = np.where(data_new[:,1] > top_100[-1]) 
print(data_new[:,2][indexes].mean(),'- среднее кол-во')

6.616161616161616 - среднее кол-во


In [538]:
#2
data_new[(np.argsort(data_new[:,1])[::-1][:100])][:,2].mean()

6.61

11. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае. Выведите процент "простых" рецептов в датасете.

In [598]:
#1
true_false = (np.where(data_new[:, 1] < 20,  1,0) * np.where(data_new[:, 2] < 5,  1,0))
np.column_stack((data_new, true_false))

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

In [613]:
print((true_false.sum()  / len(true_false)) * 100, '- %')

5.093 - %


In [615]:
#2
true_false_2 = np.where((data_new[:, 1] < 20) & (data_new[:, 2] < 5), 1,0)
np.column_stack((data_new, true_false_2))


array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

In [616]:
print((true_false_2.sum()  / len(true_false_2)) * 100, '- %')

5.093 - %


In [617]:
# data_new[:,1] < 20, data_new[:,2] < 5

12. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет не менее 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [685]:
def type_recp(minutes):
    return np.where(minutes < 10, 0, np.where(minutes < 20, 1, 2))

group_recp = type_recp(data_new[:, 1]).reshape((data_new.shape[0],))



In [686]:
new_matr = np.column_stack((data_new, group_recp))

In [687]:
np.unique(new_matr[:,3], return_index = True)


(array([0, 1, 2]), array([3, 2, 0], dtype=int64))

13. Пусть в среднем одна минута работы повара стоит ресторану 5 ед., а средняя стоимость одного ингредиента составляет 10 ед. 
Создайте вектор-столбец `numpy`, содержащий данную информацию. Посчитайте среднюю стоимость приготовления для каждого из первых 10 рецептов в наборе данных.

In [641]:
twel_task = (data_new[:,2] * 10  + data_new[:,1]*5)[:11]
np.column_stack((data_new[:11,:], twel_task))

array([[127244,     60,     16,    460],
       [ 23891,     25,      7,    195],
       [ 94746,     10,      6,    110],
       [ 67660,      5,      6,     85],
       [157911,     60,     14,    440],
       [152828,     40,      7,    270],
       [ 33941,     18,      9,    180],
       [446597,     15,      5,    125],
       [366174,      7,      9,    125],
       [ 74205,     20,      7,    170],
       [504666,     65,     20,    525]])